services:
  - type: web
    name: financial-ai-agent
    runtime: python
    python:
      version: "3.9"
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: QUESTIONNAIRE_SERVICE_URL
        value: your-questionnaire-service-url  # Set this in Render dashboard
    plan: standard  # Minimum for Phi-2 (2GB RAM)